credentials:
  usernames:
    testuser:
      email: testuser@email.com
      name: Test User
      password: '$2b$12$KIXQ1Q6QwQwQwQwQwQwQwOQwQwQwQwQwQwQwQwQwQwQwQwQwQwQw'  # password: test123
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
